# Generated by Django 4.1 on 2023-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=264)),
                ('Lastname', models.CharField(max_length=264)),
                ('Email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
